### ISSUE TITLE
Understanding "coding potential" in TransDecoder.Predict

### ISSUE THREAD

**Issue by gmartinezredondo** [TransDecoder/TransDecoder#123]
Hi!!

In our research group, we are trying to have a proxy of the gene repertoire of non-model animals for further comparative genomics and phylogenomics analysis. For that, we have de novo assembled the transcriptome using Trinity and wanted to find protein-coding genes using TransDecoder. However, while reading the manual and seeing the number of ORFs predicted by TransDecoder.LongORFs and TransDecoder.Predict we wondered how TransDecoder.Predict assesses the coding potential of a sequence. We read the manual and know that you use an HMM trained using the top 500 sequences, but we have some questions regarding this:

1. Why do we use 500 sequences when we later reevaluate the whole list of sequences?
2. Is this number enough for including the whole variability of an initial pool of more than 20000 sequences (40000, 50000 or even more)?
3. Where does this default 500 number come from? Have you compared the results obtained when using a higher value?
4. How is this related to the coding potential of a sequence?

Thanks in advance,

Gemma

**Comment by brianjohnhaas** [comment]
It's assumed that 500 coding sequences is enough to train the statistics regarding codon usage.  Sequences are selected so that they are both long (likely to be correct coding regions based on length alone) and sufficiently different in sequence (exclude isoforms or close paralogs).  500 was chosen pretty arbitrarily - just needs to be sufficiently high and representative.  The more other coding regions have codon usage similar to these training entries, the better their coding potential.
